### ISSUE TITLE
Missing directory in gem

### ISSUE THREAD

**Issue by obromios** [clbustos/minimization#7]
I included ```minimization``` in my gemfile, but when I tried to use the Nelder-Mead method
I had an error indicating the constant ```Minimization::NelderMead``` was not being found. When I looked at the installed gem lib directory
`ls .rvm/gems/ruby-2.4.4@app_name_2.4.4/gems/minimization-0.2.3/lib`
it returned:
`minimization	minimization.rb`
i.e. there was no ```multidim``` directory, so no ```nelder_mead.rb``` so no ```Minimization::NelderMead``` constant.
If I cloned the project directly from github and loaded that in my gemfile, the ```lib/multidim``` directory is there, and the ```Minimization::NelderMead``` constant is loaded.

Am I doing something wrong, or is version 0.2.3 of the gem actually missing the ```lib/multidim``` directory?

**Comment by clbustos** [comment]
You're right! Thanks for noticing. I updated the package to include the missing directory.
